#!/usr/local/sbin/charm-env python3

from lib_weechat import WeechatHelper
from charmhelpers.core import hookenv

helper = WeechatHelper()
password = helper.kv.get('relay-password')
hookenv.action_set({'outcome': 'success',
		    'password': password})
